baseurl = "https://kube-logging.dev/"
buildDrafts = false
#googleAnalytics = "G-FIXME"

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
#id = "G-FIXME"

[params]

url_latest_version = "https://kube-logging.dev/"