name: Publish version 4.4

env:
  doc_versionnumber: "4.4"

on:
  push:
    branches:
      - release-4.4
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      id-token: write
    
    concurrency:
      group: "pages"
      cancel-in-progress: false
    
    environment:
      name: github-pages-test
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          ref: release-4.4
          submodules: 'recursive'

      - name: Set up Pages
        id: pages
        uses: actions/configure-pages@1f0c5cde4bc74cd7e1254d0cb4de8d49e9068c7d # v4.0.0

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@16361eb4acea8698b220b76c0d4e84e1fd22c61d # v2.6.0
        with:
          hugo-version: '0.110.0'
          extended: true

      - name: Set up Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd themes/docsy
          npm install

      - name: Set up PostCSS
        run: npm install --save-dev autoprefixer postcss-cli postcss

      - name: Build
        run: hugo --environment production --baseURL ${{ steps.pages.outputs.base_url }}/${{ env.doc_versionnumber }}/

      # - name: Upload artifact
      #   uses: actions/upload-pages-artifact@64bcae551a7b18bcb9a09042ddf1960979799187 # v1.0.8
      #   with:
      #     path: ./public/

      - name: Checkout code to update
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          ref: 'gh-pages-test'
          path: 'tmp/gh-pages'
      # - name: Display file structure
      #   run: ls -R
      - name: Copy built site to GH pages
        run: |
          rm -rf tmp/gh-pages/${{ env.doc_versionnumber }}
          mkdir -p tmp/gh-pages/${{ env.doc_versionnumber }}
          mv public/* tmp/gh-pages/${{ env.doc_versionnumber }}
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: 'Publish updated docs for ${{ env.doc_versionnumber }}, ${{ github.event.repository.pushed_at}}'
          branch: 'gh-pages-test'
          directory: 'tmp/gh-pages'
