name: Trigger submodule update

#on:
#  push:
#    branches:
#      - master

jobs:
  trigger-submodule-update:
    name: Trigger submodule update
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Trigger
        env:
          GITHUB_TOKEN: '${{ secrets.CR_PAT }}'
        run: |
          scripts/trigger-submodule-update.sh
